from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
from sklearn import linear_model,model_selection, preprocessing
from sklearn.model_selection import train_test_split
from scipy import stats
import xgboost as xgb


class Ui_MainWindow(object):

    def calculate(self):
        df = pd.read_csv('data.csv', sep=';')

        row = {"Marka": [" " + self.marka + "   "], "Seri": [" " +self.seri+ "   "], "Model": [" " +self.model+ "   "], "Yil": self.yil,
               "Yakit": [" " +self.yakit+ "   "], "Vites": [" " +self.vites+ "   "],
               "Motor Hacmi": [" " +self.motorHacmi+ "   "], "Motor Gücü": [" " +self.motorGucu+ "   "], "Km": self.km,
               "Ilan Tarihi": [" " +self.tarih+ "   "]}

        row = pd.DataFrame(row)
        kopya2 = pd.DataFrame(
            {"Marka": 0, "Seri": 0, "Model": 0, "Yil": 0, "Yakit": 0, "Vites": 0, "Motor Hacmi": 0, "Motor Gücü": 0,
             "Km": 0, "Ilan Tarihi": 0, "Fiyat":0}, index=[0])

        for c in df.columns:  # Dosyadaki stringleri sayiya çevirme // Categorical Feature Encoding
            if df[c].dtype == 'object':
                lbl = preprocessing.LabelEncoder()
                kopya = df[c].copy()
                kopya.loc[15807] = row[c].loc[0]
                kopya = lbl.fit_transform(list(kopya.values))
                kopya2[c].loc[0] = kopya[15807]
                # lbl.fit(list(df[c].values))
                df[c] = lbl.fit_transform(list(df[c].values))
        kopya2["Yil"].loc[0] = row["Yil"].loc[0]
        kopya2["Km"].loc[0] = row["Km"].loc[0]
        print(kopya2)

        X = df.drop(["Fiyat"], axis=1)
        Y = df['Fiyat']
        pre_cpy = X.copy()
        X = X.apply(stats.zscore)
        pre_x = kopya2.drop(["Fiyat"], axis=1)
        #pre_y = row['Fiyat']
        pre_cpy.loc[15807] = pre_x.loc[0]
        pre_x.loc[0] = pre_cpy.apply(stats.zscore).loc[15807]

        data_train, data_test, label_train, label_test = train_test_split(X, Y, test_size=0.3,
                                                                          random_state=434)  # 718 434 189 509 782
        eval_set = [(data_train, label_train), (data_test, label_test)]
        model = xgb.XGBRegressor(learning_rate=0.1, max_depth=14, n_estimators=1000)
        model.fit(data_train, label_train, early_stopping_rounds=500, eval_set=eval_set)
        print("XGBRegressor")
        print("Train Score:" + str(model.score(data_train, label_train) * 100))
        print("Test Score:" + str(model.score(data_test, label_test) * 100))
        self.tahmin = model.predict(pre_x)
        print(self.tahmin)
        # out = pd.DataFrame({'Actual_price': label_test, 'predict_price': tahmin.astype(int), 'Error': abs(label_test - tahmin),'Relative Error':(label_test - tahmin)*100/label_test}).head(50)
        # print(out)

    def priceShow(self):
        self.marka = self.lineEdit.text()
        self.seri = self.lineEdit_2.text()
        self.model = self.lineEdit_3.text()
        self.yil = int(self.lineEdit_4.text())
        self.yakit = self.lineEdit_5.text()
        self.vites = self.lineEdit_6.text()
        self.motorHacmi = self.lineEdit_7.text()
        self.motorGucu = self.lineEdit_8.text()
        self.km = int(self.lineEdit_9.text())
        self.tarih = self.dateEdit.text()
        #print(type(self.marka), type(self.km))
        print(self.marka, self.seri, self.model, self.yil, self.yakit, self.vites, self.motorHacmi, self.motorGucu,
              self.km, self.tarih)

        self.calculate()
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle("Car Sales Prediction")
        msg.setText("Tahmini fiyat: {}".format(self.tahmin[0]))
        msg.exec()

    def setupUi(self, MainWindow):
        MainWindow.setStyleSheet("background-image: url(dodge.jpg)")
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(644, 457)
        MainWindow.setMinimumSize(QtCore.QSize(500, 400))
        MainWindow.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.label_11)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.lineEdit_8)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.lineEdit_9)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit.setFont(font)
        # self.dateEdit.setInputMethodHints(QtCore.Qt.ImhPreferLatin|QtCore.Qt.ImhPreferNumbers)
        self.dateEdit.setDisplayFormat("dd MMMM yyyy")
        self.dateEdit.setDate(QtCore.QDate().currentDate())
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.lineEdit.setText("Audi")
        self.lineEdit_2.setText("A6")
        self.lineEdit_3.setText("A6 Sedan 2.4")
        self.lineEdit_4.setText("2005")
        self.lineEdit_5.setText("LPG & Benzin")
        self.lineEdit_6.setText("Yarı Otomatik")
        self.lineEdit_7.setText("2001 - 2500 cm3")
        self.lineEdit_8.setText("176 - 200 HP")
        self.lineEdit_9.setText("413000")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.pushButton.clicked.connect(self.priceShow)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 644, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_11.setText(_translate("MainWindow", "Araç Fiyat Tahmini"))
        self.label.setText(_translate("MainWindow", "Araç Markası:"))
        self.label_2.setText(_translate("MainWindow", "Seri:"))
        self.label_3.setText(_translate("MainWindow", "Model:"))
        self.label_4.setText(_translate("MainWindow", "Yıl:"))
        self.label_5.setText(_translate("MainWindow", "Yakıt:"))
        self.label_6.setText(_translate("MainWindow", "Vites:"))
        self.label_7.setText(_translate("MainWindow", "Motor Hacmi:"))
        self.label_8.setText(_translate("MainWindow", "Motor Gücü:"))
        self.label_9.setText(_translate("MainWindow", "Km:"))
        self.label_10.setText(_translate("MainWindow", "Fiyat Tarihi:"))
        self.pushButton.setText(_translate("MainWindow", "Fiyat Sorgula"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

